---
### Se instala Mariadb ###




- hosts:
   - next2
  become: yes
# Previos para instalar mariadb desde repos externos:

  tasks:
# apt-transport-https
  - name: Ansible apt install apt-transport-https
    apt:
      name: apt-transport-https
      state: present 

# Curl
  - name: Ansible apt install curl
    apt:
      name: curl
      state: present  

# Nos aseguramos de que /etc/apt/keyrings exista
  - name: Creates directory keyrings
    file:
      path: /etc/apt/keyrings
      state: directory

# Descargamos las keirings:
  - name: Descargamos las keirings
    ansible.builtin.command: curl -o /etc/apt/keyrings/mariadb-keyring.pgp 'https://mariadb.org/mariadb_release_signing_key.pgp'

# Creamos fichero /etc/apt/sources.list.d/mariadb.sources con su contenido:
  - name: Creamos fichero /etc/apt/sources.list.d/mariadb.sources
    ansible.builtin.blockinfile:
      path: /etc/apt/sources.list.d/mariadb.sources
      create: True
      marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK -->"
      block: |
        # MariaDB 11.1 repository list - created 2023-10-02 15:48 UTC
        # https://mariadb.org/download/
        X-Repolib-Name: MariaDB
        Types: deb
        # deb.mariadb.org is a dynamic mirror if your preferred mirror goes offline. See https://mariadb.org/mirrorbits/ for details.
        # URIs: https://deb.mariadb.org/11.1/ubuntu
        URIs: https://mirrors.up.pt/pub/mariadb/repo/11.1/ubuntu
        Suites: jammy
        Components: main main/debug
        Signed-By: /etc/apt/keyrings/mariadb-keyring.pgp


# Instalamos Mariabd-server
  - name: Update repositories cache and install "mariadb-server" package
    ansible.builtin.apt:
      name: mariadb-server
      update_cache: yes


